import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        {/* ページのタイトルを設定 */}
        <title>Create Next App</title>
        {/* ページの説明（description）メタタグを設定 */}
        <meta name="description" content="Generated by create next app" />
        {/* ビューポートの設定を行うメタタグ。
            モバイル端末での表示を最適化するための設定 */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* ファビコン（ブラウザのタブに表示される小さなアイコン）の設定 */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}
